require("Game/MapMenu/EnumFiles/ButtonType")
require("Game/MapMenu/EnumFiles/PlayerAlliesStateType")
require("Game/MapMenu/EnumFiles/PlayerOccupyStateType")
require("Game/MapMenu/EnumFiles/TiledAlliesType")
require("Game/MapMenu/EnumFiles/TiledOwnerType")
require("Game/MapMenu/EnumFiles/TiledSuperAlliesType")
require("Game/MapMenu/EnumFiles/TiledType")