//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ToLua_DG_Tweening_TweenerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ToLua_DG_Tweening_Tweener), typeof(System.Object));
		L.RegFunction("From", From);
		L.RegFunction("New", _CreateToLua_DG_Tweening_Tweener);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateToLua_DG_Tweening_Tweener(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ToLua_DG_Tweening_Tweener obj = new ToLua_DG_Tweening_Tweener();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ToLua_DG_Tweening_Tweener.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int From(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(ToLua_DG_Tweening_Tweener)))
			{
				ToLua_DG_Tweening_Tweener obj = (ToLua_DG_Tweening_Tweener)ToLua.ToObject(L, 1);
				DG.Tweening.Tweener o = obj.From();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(ToLua_DG_Tweening_Tweener), typeof(bool)))
			{
				ToLua_DG_Tweening_Tweener obj = (ToLua_DG_Tweening_Tweener)ToLua.ToObject(L, 1);
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				DG.Tweening.Tweener o = obj.From(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ToLua_DG_Tweening_Tweener.From");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

