--
-- Author: czx
-- Data: 2017/4/22 18:49:16
--
DataCardSet={}

DataCardSet[1]={ID=1, Name="名将", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=100, FreeCD=43200000, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={1,2,3}, CardSetIcon="cardbagblue"}
DataCardSet[2]={ID=2, Name="黄巾之乱", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=1200000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={4,5,6}, CardSetIcon="cardbaggold"}
DataCardSet[3]={ID=3, Name="汉室衰微", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=1200000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={7,8,9}, CardSetIcon="cardbaggreen"}
DataCardSet[4]={ID=4, Name="天下大乱", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=1200000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={10,11,12}, CardSetIcon="cardbagpurple"}
DataCardSet[5]={ID=5, Name="厉兵秣马", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=86400000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={68,69,70}, CardSetIcon="cardbagblue"}
DataCardSet[6]={ID=6, Name="群雄割据", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=86400000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={62,63}, CardSetIcon="cardbaggold"}
DataCardSet[7]={ID=7, Name="乱世英雄", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=86400000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={64,65}, CardSetIcon="cardbaggreen"}
DataCardSet[8]={ID=8, Name="南蛮入侵", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="3-5星", CloseCondition=1, CloseConditionPram1=86400000, CloseConditionPram2=0, CostType=5, PriceForOnce=200, MoreTimes=5, PriceForMore=950, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=true, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={66,67}, CardSetIcon="cardbagpurple"}
DataCardSet[9]={ID=9, Name="武将", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="1-4星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=300, MoreTimes=10, PriceForMore=2850, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={25,26,27,28}, CardSetIcon="cardbagblue"}
DataCardSet[10]={ID=10, Name="中原猛将I", ConstructionID=5, ConstructionLv=1, CardSetInnerStar="2-4星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=1000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={29,30,31}, CardSetIcon="cardbaggold"}
DataCardSet[11]={ID=11, Name="战国大名I", ConstructionID=5, ConstructionLv=2, CardSetInnerStar="2-4星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=1000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={32,33,34}, CardSetIcon="cardbaggreen"}
DataCardSet[12]={ID=12, Name="暗黑时代I", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="2-4星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=1000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={35,36,37}, CardSetIcon="cardbagpurple"}
DataCardSet[13]={ID=13, Name="群雄鹊起I", ConstructionID=25, ConstructionLv=5, CardSetInnerStar="2-4星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=1000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={38,39,40}, CardSetIcon="cardbagblue"}
DataCardSet[14]={ID=14, Name="中原猛将II", ConstructionID=19, ConstructionLv=5, CardSetInnerStar="2-5星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=2000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={46,47,48,49}, CardSetIcon="cardbaggold"}
DataCardSet[15]={ID=15, Name="战国大名II", ConstructionID=21, ConstructionLv=5, CardSetInnerStar="2-5星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=2000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={50,51,52,53}, CardSetIcon="cardbaggreen"}
DataCardSet[16]={ID=16, Name="暗黑时代II", ConstructionID=23, ConstructionLv=5, CardSetInnerStar="2-5星", CloseCondition=3, CloseConditionPram1=0, CloseConditionPram2=0, CostType=4, PriceForOnce=2000, MoreTimes=1, PriceForMore=0, DrawEveryDay=5, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={54,55,56,57}, CardSetIcon="cardbagpurple"}
DataCardSet[17]={ID=17, Name="合纵连横", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={62,63}, CardSetIcon="cardbaggold"}
DataCardSet[18]={ID=18, Name="霸王崛起", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={64,65}, CardSetIcon="cardbaggreen"}
DataCardSet[19]={ID=19, Name="不列颠雄狮", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={66,67}, CardSetIcon="cardbagpurple"}
DataCardSet[20]={ID=20, Name="血腥红风", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={68,69,70}, CardSetIcon="cardbagblue"}
DataCardSet[21]={ID=21, Name="五子良将", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={16,17,18}, CardSetIcon="cardbaggold"}
DataCardSet[22]={ID=22, Name="洛阳大火", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={19,20,21}, CardSetIcon="cardbaggreen"}
DataCardSet[23]={ID=23, Name="借东风", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=4, CloseConditionPram1=86400000, CloseConditionPram2=1, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock8", CardSetPicGray="RecruitBlock8grey", CardLootArray={22,23,24}, CardSetIcon="cardbagpurple"}
DataCardSet[24]={ID=24, Name="新手卡包", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=2, CloseConditionPram1=0, CloseConditionPram2=1, CostType=4, PriceForOnce=100, MoreTimes=2, PriceForMore=200, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock9", CardSetPicGray="RecruitBlock9grey", CardLootArray={107}, CardSetIcon="cardbagpurple"}
DataCardSet[25]={ID=25, Name="全四星武将卡包", ConstructionID=0, ConstructionLv=0, CardSetInnerStar="", CloseCondition=1, CloseConditionPram1=86400000, CloseConditionPram2=0, CostType=0, PriceForOnce=0, MoreTimes=1, PriceForMore=0, DrawEveryDay=0, JadeSetDiscountPrice=0, FreeCD=0, CombineToBasicCardSet=false, CardSetPic="RecruitBlock6", CardSetPicGray="RecruitBlock6grey", CardLootArray={109}, CardSetIcon="cardbagpurple"}

return DataCardSet
