--
-- Author: czx
-- Data: 2017/4/19 9:37:04
--
DataClickPanelType={}

DataClickPanelType[1]={ID=1, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=4, Button={1}, Color=8}
DataClickPanelType[2]={ID=2, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=4, Button={1}, Color=8}
DataClickPanelType[3]={ID=3, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=3, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[4]={ID=4, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=3, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[5]={ID=5, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=4, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[6]={ID=6, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=4, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[7]={ID=7, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=5, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[8]={ID=8, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=5, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[9]={ID=9, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=6, TargetOwnType=1, Type=4, Button={11}, Color=5}
DataClickPanelType[10]={ID=10, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=4, Button={1}, Color=8}
DataClickPanelType[11]={ID=11, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=4, Button={1}, Color=8}
DataClickPanelType[12]={ID=12, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=2, TargetOwnType=1, Type=4, Button={5}, Color=1}
DataClickPanelType[13]={ID=13, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=2, TargetOwnType=1, Type=4, Button={1}, Color=2}
DataClickPanelType[14]={ID=14, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=3, TargetOwnType=1, Type=4, Button={1}, Color=2}
DataClickPanelType[15]={ID=15, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=3, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[16]={ID=16, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=4, TargetOwnType=1, Type=4, Button={1}, Color=6}
DataClickPanelType[17]={ID=17, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=4, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[18]={ID=18, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=5, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[19]={ID=19, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=5, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[20]={ID=20, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=6, TargetOwnType=1, Type=4, Button={11}, Color=5}
DataClickPanelType[21]={ID=21, AlliesState=1, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={7,2,5,3,4}, Color=4}
DataClickPanelType[22]={ID=22, AlliesState=1, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={10,6,5}, Color=4}
DataClickPanelType[23]={ID=23, AlliesState=1, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={5}, Color=4}
DataClickPanelType[24]={ID=24, AlliesState=1, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={9,5}, Color=4}
DataClickPanelType[25]={ID=25, AlliesState=1, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={9,5}, Color=4}
DataClickPanelType[26]={ID=26, AlliesState=1, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={5}, Color=4}
DataClickPanelType[27]={ID=27, AlliesState=1, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=1, Button={7,2,5,3,4}, Color=4}
DataClickPanelType[28]={ID=28, AlliesState=1, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=2, Button={10,6,5}, Color=4}
DataClickPanelType[29]={ID=29, AlliesState=1, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=3, Button={5}, Color=4}
DataClickPanelType[30]={ID=30, AlliesState=1, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=5, Button={9,5}, Color=4}
DataClickPanelType[31]={ID=31, AlliesState=1, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=6, Button={9,5}, Color=4}
DataClickPanelType[32]={ID=32, AlliesState=1, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=7, Button={5}, Color=4}
DataClickPanelType[33]={ID=33, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=8}
DataClickPanelType[34]={ID=34, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=8}
DataClickPanelType[35]={ID=35, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=8}
DataClickPanelType[36]={ID=36, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=8}
DataClickPanelType[37]={ID=37, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=8}
DataClickPanelType[38]={ID=38, AlliesState=1, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=8}
DataClickPanelType[39]={ID=39, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=8}
DataClickPanelType[40]={ID=40, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=8}
DataClickPanelType[41]={ID=41, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=8}
DataClickPanelType[42]={ID=42, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=8}
DataClickPanelType[43]={ID=43, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=8}
DataClickPanelType[44]={ID=44, AlliesState=1, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=8}
DataClickPanelType[45]={ID=45, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[46]={ID=46, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[47]={ID=47, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[48]={ID=48, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[49]={ID=49, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[50]={ID=50, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[51]={ID=51, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[52]={ID=52, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[53]={ID=53, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[54]={ID=54, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[55]={ID=55, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[56]={ID=56, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[57]={ID=57, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[58]={ID=58, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[59]={ID=59, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[60]={ID=60, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=4, Button={1}, Color=3}
DataClickPanelType[61]={ID=61, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[62]={ID=62, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[63]={ID=63, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[64]={ID=64, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[65]={ID=65, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[66]={ID=66, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[67]={ID=67, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[68]={ID=68, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[69]={ID=69, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[70]={ID=70, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[71]={ID=71, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[72]={ID=72, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[73]={ID=73, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[74]={ID=74, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[75]={ID=75, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[76]={ID=76, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[77]={ID=77, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[78]={ID=78, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[79]={ID=79, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[80]={ID=80, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[81]={ID=81, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[82]={ID=82, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[83]={ID=83, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[84]={ID=84, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[85]={ID=85, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[86]={ID=86, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[87]={ID=87, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[88]={ID=88, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[89]={ID=89, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[90]={ID=90, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[91]={ID=91, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[92]={ID=92, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[93]={ID=93, AlliesState=1, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[94]={ID=94, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=1, Button={11}, Color=5}
DataClickPanelType[95]={ID=95, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=2, Button={11}, Color=5}
DataClickPanelType[96]={ID=96, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=3, Button={11}, Color=5}
DataClickPanelType[97]={ID=97, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=5, Button={11}, Color=5}
DataClickPanelType[98]={ID=98, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=6, Button={11}, Color=5}
DataClickPanelType[99]={ID=99, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=7, Button={11}, Color=5}
DataClickPanelType[100]={ID=100, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[101]={ID=101, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[102]={ID=102, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[103]={ID=103, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[104]={ID=104, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[105]={ID=105, AlliesState=1, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[106]={ID=106, AlliesState=2, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={7,2,5,3,4}, Color=4}
DataClickPanelType[107]={ID=107, AlliesState=2, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={10,6,5}, Color=4}
DataClickPanelType[108]={ID=108, AlliesState=2, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={5}, Color=4}
DataClickPanelType[109]={ID=109, AlliesState=2, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={9,5}, Color=4}
DataClickPanelType[110]={ID=110, AlliesState=2, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={9,5}, Color=4}
DataClickPanelType[111]={ID=111, AlliesState=2, OccupyState=1, OwnType=1, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={5}, Color=4}
DataClickPanelType[112]={ID=112, AlliesState=2, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=1, Button={7,2,5,3,4}, Color=4}
DataClickPanelType[113]={ID=113, AlliesState=2, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=2, Button={10,6,5}, Color=4}
DataClickPanelType[114]={ID=114, AlliesState=2, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=3, Button={5}, Color=4}
DataClickPanelType[115]={ID=115, AlliesState=2, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=5, Button={9,5}, Color=4}
DataClickPanelType[116]={ID=116, AlliesState=2, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=6, Button={9,5}, Color=4}
DataClickPanelType[117]={ID=117, AlliesState=2, OccupyState=2, OwnType=1, OtherAlliesState=1, TargetOwnType=3, Type=7, Button={5}, Color=4}
DataClickPanelType[118]={ID=118, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=8}
DataClickPanelType[119]={ID=119, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=8}
DataClickPanelType[120]={ID=120, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=8}
DataClickPanelType[121]={ID=121, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=8}
DataClickPanelType[122]={ID=122, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=8}
DataClickPanelType[123]={ID=123, AlliesState=2, OccupyState=1, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=8}
DataClickPanelType[124]={ID=124, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=8}
DataClickPanelType[125]={ID=125, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=8}
DataClickPanelType[126]={ID=126, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=8}
DataClickPanelType[127]={ID=127, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=8}
DataClickPanelType[128]={ID=128, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=8}
DataClickPanelType[129]={ID=129, AlliesState=2, OccupyState=2, OwnType=2, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=8}
DataClickPanelType[130]={ID=130, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[131]={ID=131, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[132]={ID=132, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[133]={ID=133, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[134]={ID=134, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[135]={ID=135, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[136]={ID=136, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=1, Button={5}, Color=7}
DataClickPanelType[137]={ID=137, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=2, Button={5}, Color=7}
DataClickPanelType[138]={ID=138, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=3, Button={5}, Color=7}
DataClickPanelType[139]={ID=139, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=5, Button={5}, Color=7}
DataClickPanelType[140]={ID=140, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=6, Button={5}, Color=7}
DataClickPanelType[141]={ID=141, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=7, Button={5}, Color=7}
DataClickPanelType[142]={ID=142, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[143]={ID=143, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[144]={ID=144, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[145]={ID=145, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[146]={ID=146, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[147]={ID=147, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[148]={ID=148, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[149]={ID=149, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[150]={ID=150, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[151]={ID=151, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[152]={ID=152, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[153]={ID=153, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[154]={ID=154, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=1, Button={1}, Color=3}
DataClickPanelType[155]={ID=155, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=2, Button={1}, Color=3}
DataClickPanelType[156]={ID=156, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=3, Button={1}, Color=3}
DataClickPanelType[157]={ID=157, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=5, Button={1}, Color=3}
DataClickPanelType[158]={ID=158, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=6, Button={1}, Color=3}
DataClickPanelType[159]={ID=159, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=2, Type=7, Button={1}, Color=3}
DataClickPanelType[160]={ID=160, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[161]={ID=161, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[162]={ID=162, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[163]={ID=163, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[164]={ID=164, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[165]={ID=165, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=1, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[166]={ID=166, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=1, Button={5}, Color=1}
DataClickPanelType[167]={ID=167, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=2, Button={5}, Color=1}
DataClickPanelType[168]={ID=168, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=3, Button={5}, Color=1}
DataClickPanelType[169]={ID=169, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=5, Button={5}, Color=1}
DataClickPanelType[170]={ID=170, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=6, Button={5}, Color=1}
DataClickPanelType[171]={ID=171, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=7, Button={5}, Color=1}
DataClickPanelType[172]={ID=172, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=1, Button={1}, Color=2}
DataClickPanelType[173]={ID=173, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=2, Button={1}, Color=2}
DataClickPanelType[174]={ID=174, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=3, Button={1}, Color=2}
DataClickPanelType[175]={ID=175, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=5, Button={8}, Color=2}
DataClickPanelType[176]={ID=176, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=6, Button={1}, Color=2}
DataClickPanelType[177]={ID=177, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=7, Button={1}, Color=2}
DataClickPanelType[178]={ID=178, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=1, Button={1}, Color=2}
DataClickPanelType[179]={ID=179, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=2, Button={1}, Color=2}
DataClickPanelType[180]={ID=180, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=3, Button={1}, Color=2}
DataClickPanelType[181]={ID=181, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=5, Button={1}, Color=2}
DataClickPanelType[182]={ID=182, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=6, Button={1}, Color=2}
DataClickPanelType[183]={ID=183, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=1, Type=7, Button={1}, Color=2}
DataClickPanelType[184]={ID=184, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=1, Button={1}, Color=2}
DataClickPanelType[185]={ID=185, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=2, Button={1}, Color=2}
DataClickPanelType[186]={ID=186, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=3, Button={1}, Color=2}
DataClickPanelType[187]={ID=187, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=5, Button={1}, Color=2}
DataClickPanelType[188]={ID=188, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=6, Button={1}, Color=2}
DataClickPanelType[189]={ID=189, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=2, TargetOwnType=3, Type=7, Button={1}, Color=2}
DataClickPanelType[190]={ID=190, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=1, Button={1}, Color=2}
DataClickPanelType[191]={ID=191, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=2, Button={1}, Color=2}
DataClickPanelType[192]={ID=192, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=3, Button={1}, Color=2}
DataClickPanelType[193]={ID=193, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=5, Button={1}, Color=2}
DataClickPanelType[194]={ID=194, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=6, Button={1}, Color=2}
DataClickPanelType[195]={ID=195, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=7, Button={1}, Color=2}
DataClickPanelType[196]={ID=196, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=1, Button={5}, Color=7}
DataClickPanelType[197]={ID=197, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=2, Button={5}, Color=7}
DataClickPanelType[198]={ID=198, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=3, Button={5}, Color=7}
DataClickPanelType[199]={ID=199, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=5, Button={5}, Color=7}
DataClickPanelType[200]={ID=200, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=6, Button={5}, Color=7}
DataClickPanelType[201]={ID=201, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=7, Button={5}, Color=7}
DataClickPanelType[202]={ID=202, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[203]={ID=203, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[204]={ID=204, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[205]={ID=205, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[206]={ID=206, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[207]={ID=207, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[208]={ID=208, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[209]={ID=209, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[210]={ID=210, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[211]={ID=211, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[212]={ID=212, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[213]={ID=213, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[214]={ID=214, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=1, Button={1}, Color=3}
DataClickPanelType[215]={ID=215, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=2, Button={1}, Color=3}
DataClickPanelType[216]={ID=216, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=3, Button={1}, Color=3}
DataClickPanelType[217]={ID=217, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=5, Button={1}, Color=3}
DataClickPanelType[218]={ID=218, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=6, Button={1}, Color=3}
DataClickPanelType[219]={ID=219, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=2, Type=7, Button={1}, Color=3}
DataClickPanelType[220]={ID=220, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[221]={ID=221, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[222]={ID=222, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[223]={ID=223, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[224]={ID=224, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[225]={ID=225, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=3, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[226]={ID=226, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=1, Button={1}, Color=6}
DataClickPanelType[227]={ID=227, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=2, Button={1}, Color=6}
DataClickPanelType[228]={ID=228, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=3, Button={1}, Color=6}
DataClickPanelType[229]={ID=229, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=5, Button={1}, Color=6}
DataClickPanelType[230]={ID=230, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=6, Button={1}, Color=6}
DataClickPanelType[231]={ID=231, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=7, Button={1}, Color=6}
DataClickPanelType[232]={ID=232, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=1, Button={5}, Color=7}
DataClickPanelType[233]={ID=233, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=2, Button={5}, Color=7}
DataClickPanelType[234]={ID=234, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=3, Button={5}, Color=7}
DataClickPanelType[235]={ID=235, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=5, Button={5}, Color=7}
DataClickPanelType[236]={ID=236, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=6, Button={5}, Color=7}
DataClickPanelType[237]={ID=237, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=7, Button={5}, Color=7}
DataClickPanelType[238]={ID=238, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[239]={ID=239, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[240]={ID=240, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[241]={ID=241, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[242]={ID=242, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[243]={ID=243, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[244]={ID=244, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[245]={ID=245, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[246]={ID=246, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[247]={ID=247, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[248]={ID=248, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[249]={ID=249, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[250]={ID=250, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=1, Button={1}, Color=3}
DataClickPanelType[251]={ID=251, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=2, Button={1}, Color=3}
DataClickPanelType[252]={ID=252, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=3, Button={1}, Color=3}
DataClickPanelType[253]={ID=253, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=5, Button={1}, Color=3}
DataClickPanelType[254]={ID=254, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=6, Button={1}, Color=3}
DataClickPanelType[255]={ID=255, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=2, Type=7, Button={1}, Color=3}
DataClickPanelType[256]={ID=256, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[257]={ID=257, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[258]={ID=258, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[259]={ID=259, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[260]={ID=260, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[261]={ID=261, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=4, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[262]={ID=262, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[263]={ID=263, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[264]={ID=264, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[265]={ID=265, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[266]={ID=266, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[267]={ID=267, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[268]={ID=268, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=1, Button={5}, Color=7}
DataClickPanelType[269]={ID=269, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=2, Button={5}, Color=7}
DataClickPanelType[270]={ID=270, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=3, Button={5}, Color=7}
DataClickPanelType[271]={ID=271, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=5, Button={5}, Color=7}
DataClickPanelType[272]={ID=272, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=6, Button={5}, Color=7}
DataClickPanelType[273]={ID=273, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=7, Button={5}, Color=7}
DataClickPanelType[274]={ID=274, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[275]={ID=275, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[276]={ID=276, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[277]={ID=277, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[278]={ID=278, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[279]={ID=279, AlliesState=2, OccupyState=1, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[280]={ID=280, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=1, Button={1}, Color=3}
DataClickPanelType[281]={ID=281, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=2, Button={1}, Color=3}
DataClickPanelType[282]={ID=282, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=3, Button={1}, Color=3}
DataClickPanelType[283]={ID=283, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=5, Button={1}, Color=3}
DataClickPanelType[284]={ID=284, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=6, Button={1}, Color=3}
DataClickPanelType[285]={ID=285, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=1, Type=7, Button={1}, Color=3}
DataClickPanelType[286]={ID=286, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=1, Button={1}, Color=3}
DataClickPanelType[287]={ID=287, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=2, Button={1}, Color=3}
DataClickPanelType[288]={ID=288, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=3, Button={1}, Color=3}
DataClickPanelType[289]={ID=289, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=5, Button={1}, Color=3}
DataClickPanelType[290]={ID=290, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=6, Button={1}, Color=3}
DataClickPanelType[291]={ID=291, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=2, Type=7, Button={1}, Color=3}
DataClickPanelType[292]={ID=292, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[293]={ID=293, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[294]={ID=294, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[295]={ID=295, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[296]={ID=296, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[297]={ID=297, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=5, TargetOwnType=3, Type=7, Button={1}, Color=3}
DataClickPanelType[298]={ID=298, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=1, Button={11}, Color=5}
DataClickPanelType[299]={ID=299, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=2, Button={11}, Color=5}
DataClickPanelType[300]={ID=300, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=3, Button={11}, Color=5}
DataClickPanelType[301]={ID=301, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=5, Button={11}, Color=5}
DataClickPanelType[302]={ID=302, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=6, Button={11}, Color=5}
DataClickPanelType[303]={ID=303, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=1, Type=7, Button={11}, Color=5}
DataClickPanelType[304]={ID=304, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=2, Type=1, Button={1}, Color=3}
DataClickPanelType[305]={ID=305, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=2, Type=2, Button={1}, Color=3}
DataClickPanelType[306]={ID=306, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=2, Type=3, Button={1}, Color=3}
DataClickPanelType[307]={ID=307, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=2, Type=5, Button={1}, Color=3}
DataClickPanelType[308]={ID=308, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=2, Type=6, Button={1}, Color=3}
DataClickPanelType[309]={ID=309, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=2, Type=7, Button={1}, Color=3}
DataClickPanelType[310]={ID=310, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=1, Button={1}, Color=3}
DataClickPanelType[311]={ID=311, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=2, Button={1}, Color=3}
DataClickPanelType[312]={ID=312, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=3, Button={1}, Color=3}
DataClickPanelType[313]={ID=313, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=5, Button={1}, Color=3}
DataClickPanelType[314]={ID=314, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=6, Button={1}, Color=3}
DataClickPanelType[315]={ID=315, AlliesState=2, OccupyState=2, OwnType=3, OtherAlliesState=6, TargetOwnType=3, Type=7, Button={1}, Color=3}

return DataClickPanelType
